"""Initial

Revision ID: 427bfd4555df
Revises: 
Create Date: 2023-01-21 14:29:40.734782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427bfd4555df'
down_revision = None
branch_labels = None
depends_on = None

GenderType = sa.Enum('female', 'male', name='gender')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('import_id', name=op.f('pk__imports'))
    )
    op.create_table('citizens',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', GenderType, nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.import_id'], name=op.f('fk__citizens__import_id__imports')),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id', name=op.f('pk__citizens'))
    )
    op.create_table('relatives',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('relative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id', 'citizen_id'], ['citizens.import_id', 'citizens.citizen_id'], name=op.f('fk__relatives__import_id_citizen_id__citizens')),
    sa.ForeignKeyConstraint(['import_id', 'relative_id'], ['citizens.import_id', 'citizens.citizen_id'], name=op.f('fk__relatives__import_id_relative_id__citizens')),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id', 'relative_id', name=op.f('pk__relatives'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatives')
    op.drop_table('citizens')
    op.drop_table('imports')
    # ### end Alembic commands ###
    GenderType.drop(op.get_bind())
